Shell: Clean up function docs and style.

diff --git a/sh/fpath.d/gemdoc b/sh/fpath.d/gemdoc
--- a/sh/fpath.d/gemdoc
+++ b/sh/fpath.d/gemdoc
@@ -5,12 +5,12 @@
 # Usage: gemdoc GEM
 # From http://stephencelis.com/archive/2008/6/bashfully-yours-gem-shortcuts
 gemdoc () {
-    local gemdir="$(gem env gemdir)"
-    local gem="$(ls "$gemdir/doc" | grep -i "$1" | sort | tail -n1)"
-    if [[ -n "$gem" ]]; then
-        open "$gemdir/doc/$gem/rdoc/index.html"
-    else
-        echo "$(basename -- $0): gem not found: $1" 1>&2
-        return 1
-    fi
+	local gemdir="$(gem env gemdir)"
+	local gem="$(ls "$gemdir/doc" | grep -i "$1" | sort | tail -n1)"
+	if [[ -n "$gem" ]]; then
+		open "$gemdir/doc/$gem/rdoc/index.html"
+	else
+		echo "$(basename -- $0): gem not found: $1" 1>&2
+		return 1
+	fi
 }
diff --git a/sh/fpath.d/require_cmd b/sh/fpath.d/require_cmd
--- a/sh/fpath.d/require_cmd
+++ b/sh/fpath.d/require_cmd
@@ -3,12 +3,12 @@
 # Ensure that the given command is available.
 # Usage: require_cmd COMMAND
 require_cmd () {
-    if ! command which "$1" >/dev/null; then
-        echo "$(basename -- "$0"): command not found: $1" >&2
-        shift
-        if (($# != 0)); then
-            echo "$@" >&2
-        fi
-        return 1
-    fi
+	if ! has_cmd "$1"; then
+		echo "$(basename -- "$0"): command not found: $1" >&2
+		shift
+		if (($# != 0)); then
+			echo "$@" >&2
+		fi
+		return 1
+	fi
 }
